name = input("Enter your name: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height: "))
fav_pro_lan = input("Enter your favorite programming language: ")
print("===== PERSONAL PROFILE =====")
print(f"Name : {name}")
print(f"Age : {age}")
print(f"Height : {height}")
print(f"Favorite Programming Language : {fav_pro_lan}")
print("="*(len("Favorite Programming Language : {fav_pro_lan}")))